### ISSUE TITLE
Pool members cannot be given object names other than their IP addresses

### ISSUE THREAD

**Issue by rftoccijr** [F5Networks/f5-appsvcs-extension#161]
##### ISSUE TYPE
 - Feature Idea

##### AS3 BUILD/ VERSION
f5-appsvcs-3.11.0-3.noarch
```

```

##### BIGIP VERSION
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.3
  Build       0.0.5
  Edition     Point Release 3
  Date        Mon Feb 12 19:22:50 PST 2018
```

```

##### SUMMARY
When creating a pool in an application, I cannot create a pool member that has a name.  The name winds up being the IP address I put into the declaration.  For example, this declaration:

 {
     "class": "AS3",
     "action": "deploy",
     "persist": true,
     "declaration": {
         "class": "ADC",
         "schemaVersion": "3.0.0",
         "id": "SomeUID",
         "label": "Sample 1",
         "remark": "Simple HTTP Service with Round-Robin Load Balancing",
         "Sample_01": {
             "class": "Tenant",
             "A1": {
                 "class": "Application",
                 "template": "http",
                 "serviceMain": {
                     "class": "Service_HTTP",
                     "virtualAddresses": [
                         "10.0.1.10"
                     ],
                     "pool": "web_pool"
                 },
                 "web_pool": {
                     "class": "Pool",
                     "monitors": [
                         "http"
                     ],
					"members": [
						{
							"addressDiscovery": "static",
							"servicePort": 443,
							"serverAddresses": [
								"10.138.89.61"
							],
							"hostname": "remark1.hostname.local"
						},
						{
							"addressDiscovery": "static",
							"servicePort": 443,
							"serverAddresses": [
								"10.138.89.62"
							],
							"hostname": "remark2.hostname.local"
						},
						{
							"addressDiscovery": "static",
							"servicePort": 443,
							"serverAddresses": [
								"10.138.89.63"
							],
							"hostname": "remark3.hostname.local"
						}
					]
                 }
             }
         }
     }
 }

I know that the "hostname" declaration only works when the "addressDiscovery" declaration is set to "fqdn".  

In TMSH, I can create pool members with names, but then specify the IP address:

create ltm pool my_test_pool monitor http members add { hostname11.tocci.local:80 { address 10.1.20.111 } hostname12.tocci.local:80 { address 10.1.20.112 } hostname13.tocci.local:80 { address 10.1.20.113 } }

The client I'm working with would like to create the pool members with names.  He has other automation that requires this.

```

```

##### STEPS TO REPRODUCE
Basically, allow the "hostname" declaration to work when "addressDiscovery" is set to "static"

See sample declaration above.
```

```

##### EXPECTED RESULTS
To see the hostname in the pool member like this (I know this is TMSH but since I can't do it in AS3 I have to do this):

ltm pool my_test_pool {
    members {
        hostname11.tocci.local:http {
            address 10.1.20.111
            session monitor-enabled
            state down
        }
        hostname12.tocci.local:http {
            address 10.1.20.112
            session monitor-enabled
            state down
        }
        hostname13.tocci.local:http {
            address 10.1.20.113
            session monitor-enabled
            state down
        }
    }
    monitor http 
}

```

```

##### ACTUAL RESULTS
root@(bigip170)(cfg-sync Standalone)(Active)(/Common)(tmos)# cd ../Sample_01/A1/
root@(bigip170)(cfg-sync Standalone)(Active)(/Sample_01/A1)(tmos)# list ltm pool
ltm pool web_pool {
    members {
        /Sample_01/10.138.89.61:https {
            address 10.138.89.61
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Sample_01/10.138.89.62:https {
            address 10.138.89.62
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Sample_01/10.138.89.63:https {
            address 10.138.89.63
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { /Common/http }
    partition Sample_01
}
```

```

**Comment by dstokesf5** [comment]
For this feature request, what do you expect to happen when multiple addresses are given?
```json
{
    "addressDiscovery": "static",
    "servicePort": 443,
    "serverAddresses": [
        "10.138.89.61",
        "10.138.89.62"
    ],
    "hostname": "remark1.hostname.local"
}
```

**Comment by rftoccijr** [comment]
Since TMOS and the GUI don’t allow this, I expect AS3 should not allow it.  I haven’t tested iControl REST or Ansible to see if they allow it.

[https://cdn.f5.com/webcommon/email-signature/images/f5-logo-rgb-30x30.jpg]<https://f5.com/>
Richard Tocci  |  Professional Services Consultant
D (979) 219-2516  M +1-979-219-2516
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-twitter.jpg]<https://twitter.com/F5Networks/>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-linkedin.jpg]<https://www.linkedin.com/companies/f5-networks>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-facebook.jpg]<https://www.facebook.com/f5networksinc>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-youtube.jpg]<https://www.youtube.com/f5networksinc>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-devcentral.jpg]<https://devcentral.f5.com/>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-wmag-lockup.jpg]<https://f5.com/we-make-apps-go?utm_source=WMAGSIG/>

[F5 Certified BIG-IP Administrator][F5 Certified Technology Specialist]

**Comment by dstokesf5** [comment]
I'm worried about creating an odd user experience here where we end up with essentially a single and multi address mode for a member declaration. Right now a member declaration can always have multiple addresses in it. Adding the behavior as suggested for hostname would mean a member declaration can sometimes only have one address. AS3 has traditionally stayed away from any kind of per-node configuration. However, if we can come up with a solution that makes sense here without introducing user experience quirks, I am open to forwarding the feature request to the development team.

**Comment by rftoccijr** [comment]
The problem is that while you’ve tried to stay away from it, TMOS still requires that pool members automatically become nodes.  I get it, it’s a concept that’s antiquated, but since TMOS doesn’t appear to be changing, then I would think AS3 should have feature parity.

I just got done an engagement with StubHub, who was pleased with the result – I used Charon to convert their configuration to a large AS3 declaration, and they plan to move ahead with AS3 at some point to use it “properly”.  By this I mean dividing out all of their applications into tenants and deploy them with a more meaningful per-app declaration.  When I reported back that this node-level naming convention appeared to be unavailable by design, my contact there said this might be a blocking factor in adapting AS3.

serverAddress doesn’t take a node name, so that won’t work either.  The only other way around this I can think of is to create the nodes in Common, and then reference them in the declaration that way.

They use quite a bit of clunky automation right now – combinations of iControl REST, SOAP, and direct SSH calls.  They didn’t go the way of Ansible, and they like the idea of tenants separating out their apps.  I’ll continue to think on it if you’ll do the same.  Maybe a call with the customer so they can plead their case.  I copied H.B. on this so that if necessary he can facilitate a call.

[https://cdn.f5.com/webcommon/email-signature/images/f5-logo-rgb-30x30.jpg]<https://f5.com/>
Richard Tocci  |  Professional Services Consultant
D (979) 219-2516  M +1-979-219-2516
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-twitter.jpg]<https://twitter.com/F5Networks/>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-linkedin.jpg]<https://www.linkedin.com/companies/f5-networks>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-facebook.jpg]<https://www.facebook.com/f5networksinc>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-youtube.jpg]<https://www.youtube.com/f5networksinc>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-devcentral.jpg]<https://devcentral.f5.com/>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-wmag-lockup.jpg]<https://f5.com/we-make-apps-go?utm_source=WMAGSIG/>

[F5 Certified BIG-IP Administrator][F5 Certified Technology Specialist]

**Comment by markchart** [comment]
Currently the AS3 schema for `Pool` requires an array of `Pool_Member`s.  For each `Pool_Member` either you reference a pre-existing BIG-IP `node` component directly, or else you set the `addressDiscovery` property to indicate how to get the pool-member's IP addresses (which become the names of the BIG-IP pool-members as well as the BIG-IP node IP's and names).  Building from the BIG-IP feature of FQDN service discovery, one AS3 `Pool_Member` can represent multiple IP addresses (nodes), which come and go based on service discovery by any means (though of course "static" ones do not actually change dynamically).  When `addressDiscovery` is `static` then you supply all the pool-member's IP's in one array.

All that is background to this:  There is currently no good place to put the BIG-IP pool-member names desired by the OP @rftoccijr because array elements have indices, not names. The AS3 pattern is to base BIG-IP component names (that aren't auto-generated per TMOS default, like member/node names are from IP's) on AS3 object names rather than values of properties down inside AS3 objects.  That pattern is important to enable path-based references to AS3 objects and to corresponding BIG-IP components.

So if this RFE is worth doing at all, then I suggest the following solution:

Add a new `addressDiscovery` value `named` which requires a property `namedServers`
```
"properties": {
  "namedServers": {
    "title": "Named servers",
    "description": "Servers (nodes) each specified by simple-name and static IP address.  Note: use addressDiscovery=fqdn to translate a server hostname into IP address(es).",
    "type": "object",
    "additionalProperties": {
      "type": "object",
      "properties": {
        "address": {
          "title": "Server address",
          "description": "Static IP address for this server (node)",
          "type": "string",
          "format": "f5ip"
        }
      },
      "required": [ "address" ]
    },
    "propertyNames": {
      "pattern": "^[A-Za-z][0-9A-Za-z_]*$",
      "maxLength": 64
    }
  }
}
```
These objects can be reached by AS3 paths; for example, to reference the address of a pool-member you named "fooserver" you could use `/T/A/mypool/members/0/fooserver/address`.

For each named server in the pool, the BIG-IP pool member name would be set to the AS3 object name.

In theory the corresponding node could be given the AS3 object name too, but a problem could arise with node-IP-address collisions (this sort of thing is a plague on BIG-IP, see [https://support.f5.com/csp/article/K19963260](K19963260) ).  To make AS3 more robust I would suggest sticking to node-names being IP's (except when otherwise auto-assigned by TMOS) so as to avoid the need to check for and resolve collisions or reject declarations when collisions crop up.

**Comment by zivvel** [comment]
I think @markchart proposes a good solution, but I don't agree with (or undertand?) the last suggestion.  The whole reason this came up was because there are users who have mechanisms that require the node-name to be the name as opposed to the IP address.  If it causes collisions, we would get an error / a rejected declaration, just as we would when trying to add a duplicate-IP'ed node using TMSH.  That's the desired behavior.

I second this suggestion, and I would love to see it implemented.

**Comment by rftoccijr** [comment]
This is what I’m gunning towards, and thanks to the last comment for communicating that more elegantly and clearly.

[https://cdn.f5.com/webcommon/email-signature/images/f5-logo-rgb-30x30.jpg]<https://f5.com/>
Richard Tocci  |  Professional Services Consultant
D (979) 219-2516  M +1-979-219-2516
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-twitter.jpg]<https://twitter.com/F5Networks/>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-linkedin.jpg]<https://www.linkedin.com/companies/f5-networks>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-facebook.jpg]<https://www.facebook.com/f5networksinc>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-youtube.jpg]<https://www.youtube.com/f5networksinc>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-devcentral.jpg]<https://devcentral.f5.com/>
[https://cdn.f5.com/webcommon/email-signature/images/f5-sig-wmag-lockup.jpg]<https://f5.com/we-make-apps-go?utm_source=WMAGSIG/>

[F5 Certified BIG-IP Administrator][F5 Certified Technology Specialist]

**Comment by dstokesf5** [comment]
I have added AUTOTOOL-1146 to our internal product backlog to implement a solution similar to the one provided by @markchart.

**Comment by hedrickbt** [comment]
This looks like a great solution!  Without this issue being resolved and without being able to create nodes in AS3, I have to maintain iControl REST code to create nodes.

**Comment by kwinkelman-bw** [comment]
Upvote for this implementation as well. We see this issue as a regression in operations when using AS3.

**Comment by s-archer** [comment]
I have had two customers request this recently.  Is there an ETA for AUTOTOOL-1146?

**Comment by leondelyon3** [comment]
I have just had an ISP customer, Orange, requesting this feature (currently using latest version - AS3 3.32.0). 
Any update on ETA?

**Comment by kyleklabunde** [comment]
Has there been any update on this feature?

**Comment by dstokesf5** [comment]
I am prioritizing this feature for inclusion into the 3.34 release in late January. However, it is important to note that I do not have the ability to give a hard commitment on this issue.

**Comment by seattlevine** [comment]
We've started working on this but will likely tweak the [suggested API](https://github.com/F5Networks/f5-appsvcs-extension/issues/161#issuecomment-546168586). Rather than adding a new `addressDiscovery` type, we would like to keep it as `static` and allow a combination of `serverAddresses` and `namedServers` so long as there is no IP address overlap.

The updated schema for `addressDiscovery: 'static'` we are exploring is:
```
{
    "properties": {
        "serverAddresses": {
            "title": "Server addresses",
            "description": "Static IP addresses of servers (nodes)",
            "type": "array",
            "items": {
                "title": "Server address",
                "description": "Static IP address for this server (node)",
                "type": "string",
                "format": "f5ip"
            },
            "uniqueItems": true
        },
        "namedServers": {
            "title": "Named servers",
            "description": "Servers (nodes) each specified by simple-name and static IP address.  Note: use addressDiscovery=fqdn to translate a server hostname into IP address(es).",
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "address": {
                        "title": "Server address",
                        "description": "Static IP address for this server (node)",
                        "type": "string",
                        "format": "f5ip"
                    }
                },
                "required": [ "address" ]
            },
            "propertyNames": {
                "pattern": "^[A-Za-z][0-9A-Za-z_.-]*$",
                "maxLength": 64
            }
        }
    },
    "anyOf": [
        {
            "required": [ "serverAddresses" ]
        },
        {
            "required": [ "namedServers" ]
        }
    ]
}
```

**Comment by seattlevine** [comment]
Another API update. Once we dug in a bit deeper we decided that having a 'class' so deep in the declaration was also not idea. Meanwhile, in iRules, we support having an array of objects with a name property so we went with that approach here too. Further, we want to allow for other properties we might add in the future. The resulting schema is

```
{
    "properties": {
        "serverAddresses": {
            "title": "Server addresses",
            "description": "Static IP addresses of servers (nodes). Shorthand for 'servers' where you only want to specify the address property.",
            "type": "array",
            "items": {
                "title": "Server address",
                "description": "Static IP address for this server (node)",
                "type": "string",
                "format": "f5ip"
            },
            "uniqueItems": true
        },
        "servers": {
            "title": "Servers",
            "description": "Same as serverAddresses, but allowing for further specification of each node.",
            "type": "array",
            "items": {
                "title": "Servers",
                "description": "Static IP address and other details for this server (node)",
                "type": "object",
                "properties": {
                    "address": {
                        "title": "Server address",
                        "description": "Static IP address for this server (node)",
                        "type": "string",
                        "format": "f5ip"
                    },
                    "name": {
                        "title": "Name",
                        "type": "string",
                        "pattern": "^[A-Za-z][0-9A-Za-z_.-]*$",
                        "maxLength": 64
                    }
                },
                "required": [
                    "address"
                ]
            }
        }
    }
}
```

An example declaration is for a pool is
```
"web_pool": {
    "class": "Pool",
    "monitors": [
      "http"
    ],
    "members": [
        {
            "servicePort": 80,
            "serverAddresses": [
                "192.0.1.10",
                "192.0.1.11"
            ],
            "servers": [
                {
                    "name": "myNode1.example.com",
                    "address": "192.0.2.10"
                },
                {
                    "name": "myNode2.example.com",
                    "address": "192.0.2.11"
                }
            ],
            "enable": true,
            "connectionLimit": 0,
            "rateLimit": -1,
            "dynamicRatio": 1,
            "ratio": 1,
            "priorityGroup": 0,
            "adminState": "enable",
            "addressDiscovery": "static"
        }
    ]
}
```

**Comment by mkyrc** [comment]
It looks, that release [3.35](https://github.com/F5Networks/f5-appsvcs-extension/releases) is solving this feature request. Thanks!

**Comment by kyleklabunde** [comment]
how do we configure the pool member names?

**Comment by dstokesf5** [comment]
This was resolved in the 3.35.0 release.

An example can be found here: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html#specifying-a-node-name-in-a-declaration

**Comment by MashleyTC** [comment]
We are trying to use the pool_members_server feature in our AS3 template (v3.36.1). Whenever we run the declaration, we get an error:  /Canary/QA/pool_canary-qa-int_TCP_443/members/0: should have required property 'bigip'

Here is where we are calling the pool in the template:
          "pool": {
            "use": "pool_canary-qa_TCP_443"
          }
Have also tried 
          "pool": "pool_canary-qa_TCP_443"
          }

Here is the json for the pool declaration:
"pool_canary-qa_TCP_443": {
          "class": "Pool",
          "members": [
            {
              "servicePort": 443,
              "addressDiscovery": "static",
              "servers": [
                {
                  "name": "geo1-Svc01",
                  "address": "10.72.10.81"                  
                },
                {
                  "name": "geo1-Svc02",
                  "address": "10.172.10.82"
                }
              ]
            }
          ]
        }

These nodes don't exist in bigip yet so its not clear why it is asking for a bigip reference. Any ideas?

**Comment by kyleklabunde** [comment]
need to be like this, the pool members need to be by themself, not grouped together: 

{
	"servicePort": 443,
	"addressDiscovery": "static",
         "servers": [
		 {
			"name": "geo1-Svc01",
			"address": "10.72.10.81"                  
                  }
       ]         
},
{
	"servicePort": 443,
	"addressDiscovery": "static",
    "servers": [
    	{
    		"name": "geo1-Svc02",
	        "address": "10.172.10.82"
		}
	 ]
}

**Comment by MashleyTC** [comment]
Thanks for the quick response. Still getting the same error after making the change: `/Canary/QA/pool_canary-qa_TCP_443/members/0: should have required property 'bigip'`

Updated declaration:
```
"pool_canary-qa_TCP_443": {
          "class": "Pool",
          "members": [
            {
              "servicePort": 443,
              "addressDiscovery": "static",
              "servers": [
                {
                  "name": "geo1-Svc01",
                  "address": "10.72.10.81"                  
                }
               ],
               "addressDiscovery": "static",
               "servers": [
                {
                  "name": "geo1-Svc02",
                  "address": "10.172.10.82"
                }
              ]
            }
          ]
        }
```
Also, what you suggested does not line up with the doc: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html#specifying-a-node-name-in-a-declaration

This AS3 schema doesn't like it very much either: https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json

**Comment by kyleklabunde** [comment]
they seem to have it incorrect. i have talked with my SE about that. #
my declaration does look like this, and it does work

"kyle.pool.com_52000_pool": {
    "remark": "mytasknumber",
    "members": [
        {
            "addressDiscovery": "static",
            "servicePort": 52000,
            "servers": [
                {
                    "name": "server1",
                    "address": "172.1.1.12"
                }
            ]
        },
        {
            "addressDiscovery": "static",
            "servicePort": 52000,
            "servers": [
                {
                    "name": "server2",
                    "address": "172.1.1.13"
                }
            ]
        }
    ],
    "monitors": [
        {
            "use": "tcp_52000"
        }
    ],
    "slowRampTime": 300,
    "class": "Pool"
},

**Comment by MashleyTC** [comment]
I was missing a set of { } in my declaration between the two server objects. I added those but still getting the same error. 
```
"pool_canary-qa_TCP_443": {
    "class": "Pool",
    "members": [
        {
            "servicePort": 443,
            "addressDiscovery": "static",
            "servers": [
                {
                    "name": "geo1-Svc01",
                    "address": "10.72.10.81"
                }
            ]
        },
        {
            "servicePort": 443,
            "addressDiscovery": "static",
            "servers": [
                {
                    "name": "geo1-Svc02",
                    "address": "10.172.10.82"
                }
            ]
        }
    ]
}
```

I updated AS3 from 3.18.0 to 3.36.1 today by importing the latest rpm file. Could it be that something needs restarted? Docs didn't mention anything around that.

**Comment by MashleyTC** [comment]
Looks pretty similar to mine except the application template type is set to "generic" instead of "shared" and the VIP class is set to "Service_HTTPS":

    ```
"Canary": {
      "class": "Tenant",
      "QA": {
        "class": "Application",
        "template": "generic",
        "label": "Canary",
        "vs_WEB_443_CHI": {
          "class": "Service_HTTPS",
```

**Comment by kyleklabunde** [comment]
the example i was useing was for SSL-passthrough. I am also using Big-IQv8 to push to LTM v15.1.3.1. do you have any other apps in the Canary Tenent?

I think the problem is that is needs to say generic, not QA. as its the template. Canary is the Tenent. make sure to also put each app in its own tenent, or add to the declaration. bad thngs happen otherwise. I put each app in its own template so that housekeeping becomes a cinch in just deleting the template from big-iq in VS code

**Comment by MashleyTC** [comment]
I see, we plan to house each app in its own tenant. However, we have different environments for each app (LAB,QA,PROD). Alternatively, we would have a QA tenant and host all the QA applications in that tenant. Sounds like you are saying we should make a tenant for each Application_Environment and only house the one application in that tenant.

**Comment by kyleklabunde** [comment]
correct, unless. you add them to the declaration. I was thining of doing something similar, but then decided to put each FQDN in its own tenent. if the pool members need to be shared across tenents, then i add the following: 

```
 "members": [
                        {
                            "addressDiscovery": "static",
                            "servicePort": 52000,
                            "servers": [
                                {
                                    "name": "servers1",
                                    "address": "172.1.1.5"
                                }
                            ],
                            "shareNodes": true <------
                        },
```

**Comment by MashleyTC** [comment]
I removed "QA" and added "generic": `"/Canary/generic/pool_canary-qa_TCP_443/members/0: should have required property 'bigip'\"`

Then tried adding "shareNodes": true, same result. Starting to wonder if the error is misleading.

**Comment by kyleklabunde** [comment]
can you send me your full declaration?

**Comment by MashleyTC** [comment]
I need to generalize some data for security purposes. Will edit this post once its ready.

**Comment by kyleklabunde** [comment]
> I need to generalize some data for security purposes. Will edit this post once its ready.

no worries, my declaration was sterilized as well.

**Comment by MashleyTC** [comment]
```
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "urn:uuid:760075f6-8d2e-4906-92b5-e1abf5f3cb3c",
        "label": "vs_Canary_443_QA_TEST",
        "remark": "Simple HTTPS application with RR pool",
        "updateMode": "selective",
        "target": {
            "address": "<bigip>"
        },
        "Canary": {
            "class": "Tenant",
            "generic": {
                "class": "Application",
                "template": "generic",
                "label": "Canary",
                "vs_WEB_443_CHI": {
                    "class": "Service_HTTPS",
                    "virtualAddresses": [
                        "<vipIP>"
                    ],
                    "pool": "pool_canary-qa_TCP_443",
                    "serverTLS": "pr.clientTLS_Canary_QA",
                    "clientTLS": {
                        "bigip": "/Common/serverssl"
                    },
                    "profileTCP": {
                        "bigip": "/Common/clientssl"
                    },
                    "profileHTTP": {
                        "use": "pr.http_Canary_QA"
                    },
                    "iRules": [
                        "irule_CORS_Canary_QA"
                    ],
                    "policyWAF": {
                        "use": "WAF_Canary_QA"
                    },
                    "snat": {
                        "use": "SNAT_CanaryTest"
                    }
                },
                "pool_canary-qa_TCP_443": {
                    "class": "Pool",
                    "members": [
                        {
                            "shareNodes": true,
                            "servicePort": 443,
                            "addressDiscovery": "static",
                            "servers": [
                                {
                                    "name": "geo1-Svc01",
                                    "address": "10.72.10.81"
                                }
                            ]
                        },
                        {
                            "shareNodes": true,
                            "servicePort": 443,
                            "addressDiscovery": "static",
                            "servers": [
                                {
                                    "name": "geo1-Svc02",
                                    "address": "10.172.10.82"
                                }
                            ]
                        }
                    ]
                },
                "pr.clientTLS_Canary_QA": {
                    "class": "TLS_Server",
                    "certificates": [
                        {
                            "certificate": "<Cert>"
                        }
                    ]
                },
                "Trialcard.com_netops_Wildcard": {
                    "class": "Certificate",
                    "certificate": {
                        "bigip": "/Common/<cert>"
                    },
                    "privateKey": {
                        "bigip": "/Common/<certkey>"
                    }
                },
                "pr.tcp_Canary_QA": {
                    "class": "TCP_Profile"
                },
                "pr.http_Canary_QA": {
                    "class": "HTTP_Profile"
                },
                "irule_CORS_Canary_QA": {
                    "class": "iRule",
                    "iRule": {
                        "url": "https://funstuff.domain.com/irules/Cors/CORS.txt"
                    }
                },
                "HM_L7_Canary01": {
                    "class": "Monitor",
                    "monitorType": "https",
                    "send": "GET /api/v1 HTTP/1.1\r\nHost:canary-qa.trialcard.com\r\nConnection: Close\r\n\r\n",
                    "receive": "HTTP/1.(0|1) *(200|401)"
                },
                "WAF_Canary_QA": {
                    "class": "WAF_Policy",
                    "url": {
                        "url": "https://funstuff.domain.com/WAF/templates-default_AS3.xml"
                    }
                },
                "SNAT_CanaryTest": {
                    "class": "SNAT_Pool",
                    "snatAddresses": [
                        "<snatIP>"
                    ]
                }
            }
        }
    }
}
```

**Comment by MashleyTC** [comment]
Just to ensure the issue is isolated to the "servers" section, I removed it and added "serveraddresses" back in. I did not change anything else in the template. The declaration worked. I have to wonder if something on BigIP needs to be recycled after the as3 version update. Since I didn't mention it before, we are running BigIP v16.1.0 and BigIQ v7.1.0

**Comment by kyleklabunde** [comment]
so, 2 things: 

        "schemaVersion": "3.0.0", need to be 3.35.0 or greater for the plugin, since server names were introduced in 3.35

also, "generic": {. needs to be "Shared"
and template should be
                "template": "shared",

try that.

**Comment by kyleklabunde** [comment]
> Just to ensure the issue is isolated to the "servers" section, I removed it and added "serveraddresses" back in. I did not change anything else in the template. The declaration worked. I have to wonder if something on BigIP needs to be recycled after the as3 version update. Since I didn't mention it before, we are running BigIP v16.1.0 and BigIQ v7.1.0

very strange. I also have been using ACC chariot as well to do conversions.

**Comment by MashleyTC** [comment]
Switched the template type to "shared" and updated schema version to 3.35.0, no change. I will have our NetEngineers take a look tomorrow and maybe have the lab rebooted.

**Comment by kyleklabunde** [comment]
you also can open a case with Support

**Comment by MashleyTC** [comment]
Well, I actually submitted a support request a few weeks ago under devops@trilacard.com. The site said we should receive an email with instructions but we never received anything.

**Comment by MashleyTC** [comment]
Ill put in another one just in case
